### ISSUE TITLE
Unable to find Michael's contact information

### ISSUE THREAD

**Issue by SkunkworksCreativeGroupAdmin** [tw2113/upallnightmovies#11]
Apologies for posting this matter as an issue here but after spending 1/2 hour+ looking up every Google indexed page on the internet to do with you we've been unable to find a way to reliably reach you directly, and quickly. (The Wordpress.org's plugin/support page is VERY inactive, as is your Twitter.)

In need of assistance with one of your plugins that's very time sensitive. Open to possibly paying for support on the matter. Can you please contact us at: "technical@ [[our domain](https://github.com/SkunkworksCreativeGroupAdmin)]"

**Comment by tw2113** [comment]
Not sure what twitter account you were using as my primary account over at https://twitter.com/tw2113 is quite active, and my WordPress.org account is also quite active every week with regards to my plugin work for WebDevStudios.

Which plugin are you referring to?

**Comment by tw2113** [comment]
Closing as this won't be an issue regarding the repo it was opened on, but we can still discuss if/as needed
